### ISSUE TITLE
how to make fuzzingdriver  support c?

### ISSUE THREAD

**Issue by ricardo-kcc** [cryptomadco/fuzzingdriver#1]
when execute `codeql database create who-db --language=c --command=make`, it generate the error: `A fatal error occurred: There's no CodeQL extractor named 'c' installed.`

**Comment by cryptomadco** [comment]
Hi @Ricardio609 

Better to include C++ instead of C, I think CodeQL has no problem with making C programs with C++ keyword for --language.
Test it please .

Thanks.

**Comment by ricardo-kcc** [comment]
Thanks. I tried it and the result is as you said.
